local comp_utils = require("parrot.completion.utils")
local async = require("plenary.async")

describe("completion.utils", function()
  describe("resolve_path", function()
    it("should resolve relative paths correctly", function()
      async.run(function()
        local cwd = vim.fn.getcwd()
        local result = comp_utils.resolve_path("test/path", cwd)
        assert.are.equal(cwd .. "/test", result)
      end)
    end)

    it("should handle absolute paths correctly", function()
      async.run(function()
        local result = comp_utils.resolve_path("/absolute/path/file.txt", "")
        assert.are.equal("/absolute/path", result)
      end)
    end)

    it("should handle paths with trailing slashes", function()
      async.run(function()
        local result = comp_utils.resolve_path("test/path/", "")
        assert.are.equal("test/path/", result)
      end)
    end)
  end)

  describe("get_command_documentation", function()
    it("should return documentation for known commands", function()
      assert.is_string(comp_utils.get_command_documentation("file"))
      assert.is_string(comp_utils.get_command_documentation("buffer"))
      assert.is_string(comp_utils.get_command_documentation("directory"))
    end)

    it("should return empty string for unknown commands", function()
      assert.are.equal("", comp_utils.get_command_documentation("unknown"))
    end)
  end)
end)
